/**
 * Host-side staging for files declared by an agent profile's
 * `prepareAgentEnv` hook.
 *
 * Writes each {@link StagedFile} to `<saifctlPath>/.stage/<idx>` and emits
 * a `<saifctlPath>/.stage/apply.sh` that the in-container `coder-start.sh`
 * sources right after startup-script and before agent-install. The
 * `<saifctlPath>` is bind-mounted at `/saifctl` inside the coder container,
 * so the host-side path resolves to `/saifctl/.stage/...` in-container.
 *
 * Why a generated bash script (not a JSON manifest): saifctl's coder images
 * don't all ship `jq`, and shipping a bash applier with shell-quoted paths
 * is simpler than adding a JSON parser to every Dockerfile.coder.
 */

import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import type { StagedFile } from '../agent-profiles/types.js';

/**
 * Materialize a list of staged files under `<saifctlPath>/.stage/` and emit
 * `apply.sh`. Idempotent: previous staging is cleared first.
 *
 * No-op (and removes any stale `.stage/` from a prior run) when `files` is
 * empty.
 */
export async function applyStagedFiles(saifctlPath: string, files: StagedFile[]): Promise<void> {
  const stageDir = join(saifctlPath, '.stage');
  await rm(stageDir, { recursive: true, force: true });
  if (files.length === 0) return;
  await mkdir(stageDir, { recursive: true });

  const applyLines: string[] = [
    '#!/bin/bash',
    '# Auto-generated by saifctl. Applies files staged by an agent profile',
    '# prepareAgentEnv hook. Runs inside the coder container as root, after',
    '# startup-script and before agent-install. Do not edit manually.',
    'set -euo pipefail',
    '',
  ];

  for (let idx = 0; idx < files.length; idx += 1) {
    const file = files[idx];
    const srcPath = join(stageDir, String(idx));
    const content =
      file.src.kind === 'file'
        ? await (await import('node:fs/promises')).readFile(file.src.path)
        : file.src.content;
    await writeFile(srcPath, content);

    const dst = resolveDst(file.dst);
    const containerSrc = `/saifctl/.stage/${idx}`;
    const mode = file.mode ?? 0o600;
    const owner = file.owner ?? 'unpriv';

    applyLines.push(`# entry ${idx}: ${dst}`);
    applyLines.push(`mkdir -p ${shellQuote(dirname(dst))}`);
    applyLines.push(`cp ${shellQuote(containerSrc)} ${shellQuote(dst)}`);
    applyLines.push(`chmod ${mode.toString(8)} ${shellQuote(dst)}`);
    if (owner === 'unpriv') {
      applyLines.push(
        `chown "$(id -u "$SAIFCTL_UNPRIV_USER")":"$(id -g "$SAIFCTL_UNPRIV_USER")" ${shellQuote(dst)}`,
      );
    }
    applyLines.push('');
  }

  await writeFile(join(stageDir, 'apply.sh'), applyLines.join('\n'), {
    mode: 0o755,
  });
}

/**
 * Resolve `~/`, `$HOME/`, and `${HOME}/` prefixes in a profile-supplied `dst`.
 *
 * Container-side: `coder-start.sh` runs as root with `$HOME=/root`, but we
 * want unpriv-owned files to land in the unpriv user's home. The applier
 * script computes that path at runtime via `getent passwd`. Saifctl emits a
 * shell variable reference rather than a hard-coded path so the applier
 * works regardless of which Dockerfile.coder set the unpriv user.
 */
function resolveDst(dst: string): string {
  // Replace leading ~/ or $HOME/ with the runtime-computed unpriv home.
  // The applier script references "$SAIFCTL_UNPRIV_HOME" which it sets via
  // `getent passwd`; saifctl emits the placeholder here verbatim so it gets
  // expanded by the apply.sh shell at run time inside the container.
  if (dst.startsWith('~/')) {
    return `"$(getent passwd "$SAIFCTL_UNPRIV_USER" | cut -d: -f6)"/${dst.slice(2)}`;
  }
  if (dst.startsWith('$HOME/') || dst.startsWith('${HOME}/')) {
    const rest = dst.replace(/^\$\{?HOME\}?\//, '');
    return `"$(getent passwd "$SAIFCTL_UNPRIV_USER" | cut -d: -f6)"/${rest}`;
  }
  return dst;
}

/**
 * Shell-quote a path for safe use inside the generated apply.sh.
 *
 * Wraps in single quotes and escapes embedded single quotes via `'\''`. The
 * resulting `apply.sh` is bash, so this is bash-safe.
 *
 * Note: paths containing literal `$(...)` are intentionally allowed through
 * unquoted via {@link resolveDst} (we want shell expansion at run time).
 * Caller controls whether to call this on the dst or not — saifctl passes
 * already-quoted strings from resolveDst directly when they contain
 * substitutions.
 */
function shellQuote(value: string): string {
  // If the value already begins with a `"$(...)"` substitution (from
  // resolveDst), don't double-quote it. Detect and pass through.
  if (value.startsWith('"$(') || value.includes('"$(')) {
    return value;
  }
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
