# generated by datamodel-codegen:
#   filename:  workflow-schema.json
#   timestamp: 2026-05-13T17:20:02+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(min_length=1)]
    description: str | None = None
    labels: dict[str, str] | None = None
    annotations: dict[str, str] | None = None


class Type(StrEnum):
    string = 'string'
    number = 'number'
    boolean = 'boolean'
    secret = 'secret'


class Inputs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    required: bool | None = None
    default: Any | None = None


class Sources1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(min_length=1, pattern='^[a-z][a-z0-9_]*$')]
    type: Literal['github']
    url: Annotated[
        str, Field(description='Repo as `owner/repo` or full URL', min_length=1)
    ]
    ref: Annotated[str | None, Field(description='Branch / tag / commit SHA')] = None
    path: Annotated[
        str | None, Field(description='Sparse-checkout sub-path within the repo')
    ] = None
    token: Annotated[
        str | None,
        Field(
            description='GitHub access token',
            json_schema_extra={'x-saifctl-sensitive': True},
        ),
    ] = None
    save_as: Annotated[
        str,
        Field(
            alias='saveAs',
            description='Workspace-relative path; no `/workspace/` prefix; no `..` segments (§5.2)',
            min_length=1,
        ),
    ]


class Exports(StrEnum):
    string = 'string'
    number = 'number'
    integer = 'integer'
    boolean = 'boolean'
    array = 'array'
    object = 'object'


class Smtp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    host: Annotated[str, Field(min_length=1)]
    port: Annotated[int, Field(ge=1, le=65535)]
    secure: Annotated[
        bool | None, Field(description='true = implicit TLS; default false = STARTTLS')
    ] = None
    user: str | None = None
    password: Annotated[
        str | None,
        Field(
            description='SMTP password', json_schema_extra={'x-saifctl-sensitive': True}
        ),
    ] = None


class Id(RootModel[Any]):
    root: Any


class Field0(StrEnum):
    string = 'string'
    number = 'number'
    integer = 'integer'
    boolean = 'boolean'
    array = 'array'
    object = 'object'


class Sources2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    type: Literal['s3']
    uri: Annotated[
        str,
        Field(
            description='s3:// URI; trailing `/` denotes a prefix (directory)',
            min_length=1,
        ),
    ]
    region: Annotated[str, Field(description='AWS region', min_length=1)]
    endpoint: Annotated[
        str | None, Field(description='S3-compatible endpoint (MinIO / Wasabi / Ceph)')
    ] = None
    access_key_id: Annotated[
        str | None,
        Field(
            alias='accessKeyId',
            description='AWS access key ID',
            json_schema_extra={'x-saifctl-sensitive': True},
        ),
    ] = None
    secret_access_key: Annotated[
        str | None,
        Field(
            alias='secretAccessKey',
            description='AWS secret access key',
            json_schema_extra={'x-saifctl-sensitive': True},
        ),
    ] = None
    session_token: Annotated[
        str | None,
        Field(
            alias='sessionToken',
            description='AWS STS session token',
            json_schema_extra={'x-saifctl-sensitive': True},
        ),
    ] = None
    save_as: Annotated[str, Field(alias='saveAs', min_length=1)]


class Sources(RootModel[Sources1 | Sources2]):
    root: Annotated[Sources1 | Sources2, Field(discriminator='type')]


class Exports1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Field0


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    spec: Annotated[
        str,
        Field(
            description='Inline spec text OR a path to a spec file (§6.3)', min_length=1
        ),
    ]
    if_: Annotated[
        str | None, Field(alias='if', description='CEL predicate (§6.5)')
    ] = None
    exports: dict[str, Exports | Exports1] | None = None


class Sinks1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    type: Literal['s3']
    uri: Annotated[str, Field(min_length=1)]
    file: Annotated[
        str, Field(description='Workspace-source file or directory', min_length=1)
    ]
    region: Annotated[str, Field(min_length=1)]
    access_key_id: Annotated[
        str | None,
        Field(
            alias='accessKeyId',
            description='AWS access key ID',
            json_schema_extra={'x-saifctl-sensitive': True},
        ),
    ] = None
    secret_access_key: Annotated[
        str | None,
        Field(
            alias='secretAccessKey',
            description='AWS secret access key',
            json_schema_extra={'x-saifctl-sensitive': True},
        ),
    ] = None
    after: Annotated[
        str, Field(description='Bare step ref OR CEL predicate (§7.3)', min_length=1)
    ]


class Sinks2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    type: Literal['email']
    smtp: Smtp
    from_: Annotated[str, Field(alias='from', min_length=1)]
    to: Annotated[list[str], Field(min_length=1)]
    cc: list[str] | None = None
    bcc: list[str] | None = None
    subject: str | None = None
    body: str | None = None
    body_html: Annotated[bool | None, Field(alias='bodyHtml')] = None
    attachments: list[str] | None = None
    after: Annotated[str, Field(min_length=1)]


class Sinks(RootModel[Sinks1 | Sinks2]):
    root: Annotated[Sinks1 | Sinks2, Field(discriminator='type')]


class Workflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Annotated[Literal[1], Field(alias='schemaVersion')]
    metadata: Metadata
    inputs: dict[str, Inputs] | None = None
    sources: list[Sources] | None = None
    steps: Annotated[list[Step], Field(min_length=1)]
    sinks: list[Sinks] | None = None


class Model(RootModel[Workflow]):
    root: Annotated[
        Workflow,
        Field(
            json_schema_extra={
                'definitions': {
                    'Workflow': {
                        'type': 'object',
                        'properties': {
                            'schemaVersion': {'type': 'number', 'const': 1},
                            'metadata': {
                                'type': 'object',
                                'properties': {
                                    'name': {'type': 'string', 'minLength': 1},
                                    'description': {'type': 'string'},
                                    'labels': {
                                        'type': 'object',
                                        'additionalProperties': {'type': 'string'},
                                    },
                                    'annotations': {
                                        'type': 'object',
                                        'additionalProperties': {'type': 'string'},
                                    },
                                },
                                'required': ['name'],
                                'additionalProperties': False,
                            },
                            'inputs': {
                                'type': 'object',
                                'additionalProperties': {
                                    'type': 'object',
                                    'properties': {
                                        'type': {
                                            'type': 'string',
                                            'enum': [
                                                'string',
                                                'number',
                                                'boolean',
                                                'secret',
                                            ],
                                        },
                                        'required': {'type': 'boolean'},
                                        'default': {},
                                    },
                                    'required': ['type'],
                                    'additionalProperties': False,
                                },
                            },
                            'sources': {
                                'type': 'array',
                                'items': {
                                    'oneOf': [
                                        {
                                            'type': 'object',
                                            'properties': {
                                                'id': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                    'pattern': '^[a-z][a-z0-9_]*$',
                                                },
                                                'type': {
                                                    'type': 'string',
                                                    'const': 'github',
                                                },
                                                'url': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                    'description': 'Repo as `owner/repo` or full URL',
                                                },
                                                'ref': {
                                                    'type': 'string',
                                                    'description': 'Branch / tag / commit SHA',
                                                },
                                                'path': {
                                                    'type': 'string',
                                                    'description': 'Sparse-checkout sub-path within the repo',
                                                },
                                                'token': {
                                                    'type': 'string',
                                                    'description': 'GitHub access token',
                                                    'x-saifctl-sensitive': True,
                                                },
                                                'saveAs': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                    'description': 'Workspace-relative path; no `/workspace/` prefix; no `..` segments (§5.2)',
                                                },
                                            },
                                            'required': ['id', 'type', 'url', 'saveAs'],
                                            'additionalProperties': False,
                                        },
                                        {
                                            'type': 'object',
                                            'properties': {
                                                'id': {
                                                    '$ref': '#/definitions/Workflow/properties/sources/items/anyOf/0/properties/id'
                                                },
                                                'type': {
                                                    'type': 'string',
                                                    'const': 's3',
                                                },
                                                'uri': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                    'description': 's3:// URI; trailing `/` denotes a prefix (directory)',
                                                },
                                                'region': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                    'description': 'AWS region',
                                                },
                                                'endpoint': {
                                                    'type': 'string',
                                                    'description': 'S3-compatible endpoint (MinIO / Wasabi / Ceph)',
                                                },
                                                'accessKeyId': {
                                                    'type': 'string',
                                                    'description': 'AWS access key ID',
                                                    'x-saifctl-sensitive': True,
                                                },
                                                'secretAccessKey': {
                                                    'type': 'string',
                                                    'description': 'AWS secret access key',
                                                    'x-saifctl-sensitive': True,
                                                },
                                                'sessionToken': {
                                                    'type': 'string',
                                                    'description': 'AWS STS session token',
                                                    'x-saifctl-sensitive': True,
                                                },
                                                'saveAs': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                },
                                            },
                                            'required': [
                                                'id',
                                                'type',
                                                'uri',
                                                'region',
                                                'saveAs',
                                            ],
                                            'additionalProperties': False,
                                        },
                                    ],
                                    'discriminator': {'propertyName': 'type'},
                                },
                            },
                            'steps': {
                                'type': 'array',
                                'items': {
                                    'type': 'object',
                                    'properties': {
                                        'id': {
                                            '$ref': '#/definitions/Workflow/properties/sources/items/anyOf/0/properties/id'
                                        },
                                        'spec': {
                                            'type': 'string',
                                            'minLength': 1,
                                            'description': 'Inline spec text OR a path to a spec file (§6.3)',
                                        },
                                        'if': {
                                            'type': 'string',
                                            'description': 'CEL predicate (§6.5)',
                                        },
                                        'exports': {
                                            'type': 'object',
                                            'additionalProperties': {
                                                'anyOf': [
                                                    {
                                                        'type': 'string',
                                                        'enum': [
                                                            'string',
                                                            'number',
                                                            'integer',
                                                            'boolean',
                                                            'array',
                                                            'object',
                                                        ],
                                                    },
                                                    {
                                                        'type': 'object',
                                                        'properties': {
                                                            'type': {
                                                                '$ref': '#/definitions/Workflow/properties/steps/items/properties/exports/additionalProperties/anyOf/0'
                                                            }
                                                        },
                                                        'required': ['type'],
                                                        'additionalProperties': False,
                                                    },
                                                ]
                                            },
                                        },
                                    },
                                    'required': ['id', 'spec'],
                                    'additionalProperties': False,
                                },
                                'minItems': 1,
                            },
                            'sinks': {
                                'type': 'array',
                                'items': {
                                    'oneOf': [
                                        {
                                            'type': 'object',
                                            'properties': {
                                                'id': {
                                                    '$ref': '#/definitions/Workflow/properties/sources/items/anyOf/0/properties/id'
                                                },
                                                'type': {
                                                    'type': 'string',
                                                    'const': 's3',
                                                },
                                                'uri': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                },
                                                'file': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                    'description': 'Workspace-source file or directory',
                                                },
                                                'region': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                },
                                                'accessKeyId': {
                                                    'type': 'string',
                                                    'description': 'AWS access key ID',
                                                    'x-saifctl-sensitive': True,
                                                },
                                                'secretAccessKey': {
                                                    'type': 'string',
                                                    'description': 'AWS secret access key',
                                                    'x-saifctl-sensitive': True,
                                                },
                                                'after': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                    'description': 'Bare step ref OR CEL predicate (§7.3)',
                                                },
                                            },
                                            'required': [
                                                'id',
                                                'type',
                                                'uri',
                                                'file',
                                                'region',
                                                'after',
                                            ],
                                            'additionalProperties': False,
                                        },
                                        {
                                            'type': 'object',
                                            'properties': {
                                                'id': {
                                                    '$ref': '#/definitions/Workflow/properties/sources/items/anyOf/0/properties/id'
                                                },
                                                'type': {
                                                    'type': 'string',
                                                    'const': 'email',
                                                },
                                                'smtp': {
                                                    'type': 'object',
                                                    'properties': {
                                                        'host': {
                                                            'type': 'string',
                                                            'minLength': 1,
                                                        },
                                                        'port': {
                                                            'type': 'integer',
                                                            'minimum': 1,
                                                            'maximum': 65535,
                                                        },
                                                        'secure': {
                                                            'type': 'boolean',
                                                            'description': 'true = implicit TLS; default false = STARTTLS',
                                                        },
                                                        'user': {'type': 'string'},
                                                        'password': {
                                                            'type': 'string',
                                                            'description': 'SMTP password',
                                                            'x-saifctl-sensitive': True,
                                                        },
                                                    },
                                                    'required': ['host', 'port'],
                                                    'additionalProperties': False,
                                                },
                                                'from': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                },
                                                'to': {
                                                    'type': 'array',
                                                    'items': {'type': 'string'},
                                                    'minItems': 1,
                                                },
                                                'cc': {
                                                    'type': 'array',
                                                    'items': {'type': 'string'},
                                                },
                                                'bcc': {
                                                    'type': 'array',
                                                    'items': {'type': 'string'},
                                                },
                                                'subject': {'type': 'string'},
                                                'body': {'type': 'string'},
                                                'bodyHtml': {'type': 'boolean'},
                                                'attachments': {
                                                    'type': 'array',
                                                    'items': {'type': 'string'},
                                                },
                                                'after': {
                                                    'type': 'string',
                                                    'minLength': 1,
                                                },
                                            },
                                            'required': [
                                                'id',
                                                'type',
                                                'smtp',
                                                'from',
                                                'to',
                                                'after',
                                            ],
                                            'additionalProperties': False,
                                        },
                                    ],
                                    'discriminator': {'propertyName': 'type'},
                                },
                            },
                        },
                        'required': ['schemaVersion', 'metadata', 'steps'],
                        'additionalProperties': False,
                    }
                },
                '$schema': 'http://json-schema.org/draft-07/schema#',
            }
        ),
    ]
